name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app with correct base
      run: |
        export NODE_ENV=production
        npm run build

    - name: Fix paths for GitHub Pages
      run: |
        # Update index.html to use relative paths
        sed -i 's|="/assets/|="./assets/|g' dist/public/index.html
        sed -i 's|="/manifest.json|="./manifest.json|g' dist/public/index.html
        
        # Update service worker path in built files
        find dist/public -name "*.js" -exec sed -i 's|"/sw.js"|"./sw.js"|g' {} \;
        
        # List final structure
        echo "Final build structure:"
        ls -la dist/public/
        echo "Index.html content:"
        head -20 dist/public/index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false